export const shopCategories = [
  { value: "fashion", label: "Fashion" },
  { value: "electronics", label: "Electronics" },
  { value: "home_appliances", label: "Home Appliances" },
  { value: "books", label: "Books" },
  { value: "beauty_health", label: "Beauty & Health" },
  { value: "sports_outdoors", label: "Sports & Outdoors" },
  { value: "toys_games", label: "Toys & Games" },
  { value: "grocery", label: "Grocery" },
  { value: "automotive", label: "Automotive" },
  { value: "jewelry_accessories", label: "Jewelry & Accessories" },
  { value: "art_crafts", label: "Art & Crafts" },
  { value: "music_movies", label: "Music & Movies" },
  { value: "pet_supplies", label: "Pet Supplies" },
  { value: "baby_products", label: "Baby Products" },
  { value: "garden_outdoor", label: "Garden & Outdoor" },
  { value: "office_supplies", label: "Office Supplies" },
  { value: "health_wellness", label: "Health & Wellness" },
  { value: "food_beverages", label: "Food & Beverages" },
  { value: "travel_luggage", label: "Travel & Luggage" },
  { value: "handmade_goods", label: "Handmade Goods" },
];
