import "./global.css";
import { Poppins } from "next/font/google";
import Providers from "./providers";

export const metadata = {
  title: "ShopNex - Admin",
  description: "Generated by create-nx-workspace",
};

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`h-screen w-screen bg-[#e0e5ec] dark:bg-[#1a1c20] font-sans antialiased overflow-hidden ${poppins.variable}`}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
